Fix/delete message
techmefr/WildChat pull request #7
Opened 2024-09-13 08:55 UTC by brrrrrbrrrr

2024-09-13 18:44 UTC, techmefr submitted a review, later dismissed

2024-09-16 07:46 UTC, sdp971 requested changes
deux console log à supprimer. J'ai vu que tu as enlevé les autres mais que tu les as laissés il y a une raison particulière peut être ?

2024-09-16 07:46 UTC, sdp971 commented on server/src/service/redis.service.ts
Il y a deux  console.log à supprimer si c'est bon

2024-09-16 09:48 UTC, techmefr approved these changes

2024-09-16 15:03 UTC, closed without merging